name: Deploy

on:
  push:
    branches: [ source ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
          
      - name: npm install & deploy
        run: |
          git config --global user.name 'Konrad Drozd'
          git config --global user.email 'drozdkonrad@gmail.com'
          npm install
          npm run deploy